export const PATTERNS = {
  AUTH_REGISTER: 'auth.register',
  AUTH_LOGIN: 'auth.login',
  AUTH_REFRESH_TOKEN: 'auth.refresh_token',
  AUTH_CHANGE_PASSWORD: 'auth.change_password',

  USER_CREATE: 'user.create',
  USER_FIND_BY_ID: 'user.findById',
  USER_FIND_ALL: 'user.findAll',
  USER_UPDATE: 'user.update',
  USER_DELETE: 'user.delete',
  USER_FIND_BY_EMAIL: 'user.findByEmail',
  USER_CHANGE_ROLE: 'user.changeRole',
  USER_UPDATE_HOST_PROFILE: 'user.updateHostProfile',
  USER_VERIFY_HOST_PROFILE: 'user.verifyHostProfile',

  GUEST_ADD_WISHLIST: 'guest.addWishlist',
  GUEST_REMOVE_WISHLIST: 'guest.removeWishlist',
  GUEST_GET_WISHLIST: 'guest.getWishlist',

  STAFF_CREATE: 'staff.register',
  STAFF_DELETE: 'staff.delete',
  STAFF_FIND_ALL: 'staff.findAll',
  STAFF_FIND_BY_ROLE: 'staff.findByRole',
  STAFF_FIND_BY_ID: 'staff.findById',
  STAFF_UPDATE: 'staff.update',
  STAFF_FIND_BY_BRANCH: 'staff.findByBranch',
  STAFF_ASSIGN_BRANCH: 'staff.assignBranch',

  ROLE_CREATE: 'role.create',
  ROLE_FIND_BY_ID_OR_NAME: 'role.findByIdOrName',
  ROLE_FIND_ALL: 'role.findAll',
  ROLE_UPDATE: 'role.update',
  ROLE_DELETE: 'role.delete',
  ROLE_FIND_BY_ID: 'role.findById',
  ROLE_ASSIGN_PERMISSIONS: 'role.assignPermissions',
  ROLE_REMOVE_PERMISSION: 'role.removePermission',
  ROLE_UPDATE_PERMISSION: 'role.updatePermission',
  ROLE_ASSIGN_USER: 'role.assignUser',

  // ===== PERMISSION =====
  PERMISSION_CREATE: 'permission.create',
  PERMISSION_FIND_BY_ID: 'permission.findById',
  PERMISSION_FIND_ALL: 'permission.findAll',
  PERMISSION_UPDATE: 'permission.update',
  PERMISSION_DELETE: 'permission.delete',

  CAR_MODEL_CREATE: 'carModel.create',
  CAR_MODEL_FIND_BY_ID: 'carModel.findById',
  CAR_MODEL_FIND_ALL: 'carModel.findAll',
  CAR_MODEL_UPDATE: 'carModel.update',
  CAR_MODEL_DELETE: 'carModel.delete',

  CAR_MAKE_CREATE: 'carMake.create',
  CAR_MAKE_FIND_BY_ID: 'carMake.findById',
  CAR_MAKE_FIND_ALL: 'carMake.findAll',
  CAR_MAKE_UPDATE: 'carMake.update',
  CAR_MAKE_DELETE: 'carMake.delete',

  CAR_CREATE: 'car.create',
  CAR_UPDATE: 'car.update',
  CAR_DELETE: 'car.delete',
  CAR_FIND_BY_ID: 'car.findById',
  CAR_FIND_ALL: 'car.findAll',
  CAR_SEARCH: 'car.search',
  CAR_LIST_BY_HOST: 'car.listByHost',
  CAR_LIST_MAKES: 'car.listMakes',
  CAR_CREATE_MAKE: 'car.createMake',
  CAR_CREATE_MODEL: 'car.createModel',

  CAR_INSURANCE_ADD: 'carInsurance.add',
  CAR_INSURANCE_UPDATE: 'carInsurance.update',
  CAR_INSURANCE_DELETE: 'carInsurance.delete',
  CAR_INSURANCE_GET_BY_CAR: 'carInsurance.getByCar',

  BOOKING_CREATE: 'booking.create',
  BOOKING_UPDATE: 'booking.update',
  BOOKING_DELETE: 'booking.delete',
  BOOKING_GET_BY_ID: 'booking.getById',
  BOOKING_GET_ALL: 'booking.getAll',

  BOOKING_CANCEL_BY_GUEST: 'booking.cancelByGuest',
  BOOKING_CONFIRM_BY_HOST: 'booking.confirmByHost',
  BOOKING_REJECT_BY_HOST: 'booking.rejectByHost',
  BOOKING_CANCEL_BY_HOST: 'booking.cancelByHost',
  BOOKING_COMPLETE_BY_HOST: 'booking.completeByHost',
  BOOKING_CANCEL_BY_ADMIN: 'booking.cancelByAdmin',

  REVIEW_CREATE: 'REVIEW_CREATE',
  REVIEW_GET_BY_ID: 'REVIEW_GET_BY_ID',
  REVIEW_GET_BY_CAR: 'REVIEW_GET_BY_CAR',
  REVIEW_GET_BY_USER: 'REVIEW_GET_BY_USER',
  REVIEW_DELETE: 'REVIEW_DELETE',

  DISPUTE_CREATE: 'DISPUTE_CREATE',
  DISPUTE_GET_BY_ID: 'DISPUTE_GET_BY_ID',
  DISPUTE_GET_BY_USER: 'DISPUTE_GET_BY_USER',
  DISPUTE_GET_ALL: 'DISPUTE_GET_ALL',
  DISPUTE_RESOLVE: 'DISPUTE_RESOLVE',
  DISPUTE_REJECT: 'DISPUTE_REJECT',
  DISPUTE_CANCEL: 'DISPUTE_CANCEL',

  PAYMENT_CREATE: 'PAYMENT_CREATE',
  PAYMENT_RELEASE_TO_HOST: 'PAYMENT_RELEASE_TO_HOST',
  PAYMENT_REFUND: 'PAYMENT_REFUND',
  PAYMENT_GET_BY_ID: 'PAYMENT_GET_BY_ID',
  PAYMENT_GET_BY_BOOKING: 'PAYMENT_GET_BY_BOOKING',
  PAYMENT_GET_BY_USER: 'PAYMENT_GET_BY_USER',
  PAYMENT_GET_ALL: 'PAYMENT_GET_ALL',
} as const;
